# Notebook destinado a Parte 1 - Resolvendo um Problema Linearmente Separável do Projeto 2 de Redes Neurais 2020.1
## Colaboradores: Jakson Protázio e Nadine Brito

Primeiro importamos as bibliotecas necessárias.

In [23]:
import numpy as np
import random

Em seguida realizamos a leitura do dataset. 

In [24]:
dataset=np.fromfile('data/dataAll.txt')
linhas = len(dataset)//3
colunas=3
dataset=dataset.reshape(linhas, colunas)
print(dataset)

[[-363.7884  244.1423    0.    ]
 [ 328.7572 -256.7658    1.    ]
 [-164.9827  613.2164    0.    ]
 ...
 [ 872.4311  669.1192    1.    ]
 [ 822.6894 -702.6489    1.    ]
 [-140.147   734.0983    0.    ]]


No passo seguinte iremos iniciar o preenchimento do vetor de pesos.

In [25]:
pesos = np.array([random.uniform(-0.5,0.5),random.uniform(-0.5,0.5),random.uniform(-0.5,0.5)])
    
print(pesos)

[-0.27655766  0.28003694 -0.0502662 ]


Agora verificamos, através de uma soma ponderada e uma função de ativação, se os pesos precisam de ajuste. Para isso, primeiro, preenchemos um vetor com as entradas do dataset.

In [26]:
entradas = np.array([[-1, dataset[0,0], dataset[0,1]]])
for i in range(1, linhas):
    entradas = np.append(entradas, [[-1, dataset[i,0], dataset[i,1]]], axis=0)
print(entradas)

[[  -1.     -363.7884  244.1423]
 [  -1.      328.7572 -256.7658]
 [  -1.     -164.9827  613.2164]
 ...
 [  -1.      872.4311  669.1192]
 [  -1.      822.6894 -702.6489]
 [  -1.     -140.147   734.0983]]


Agora definimos a função que irá realizar a soma ponderada.

In [27]:
def soma(entradas,pesos):
    return(np.dot(entradas,pesos))

Em seguida definimos a função de ativação. Nesse cenário, a pedido do enunciado, adotou-se a função de ativação degrau com limiar sendo 0.

In [28]:
def ativacao(saida):
    if(saida >= 0):
        return 1
    else:
        return 0  

Definimos também a função de ajuste de pesos.

In [29]:
def ajusta(pesos_atuais, yd, y, x):
    taxa = 0.1
    erro = (yd-y)
    mult = taxa*erro
    result = pesos_atuais + np.dot(mult,x)
    return result


A função verifica, será responsável por fazer a chamada das funções para realizar a soma ponderada, função de ativação e a função de ajuste de pesos.

In [30]:
def verifica(pesos):
    qtde_ajuste = 0
    n = len(entradas)
    
    for i in range(n):
        soma_saida = soma(entradas[i], pesos)
        y = ativacao(soma_saida)
        if(y != dataset[i,2]):
            pesos = ajusta(pesos,dataset[i,2],y,entradas[i])
            qtde_ajuste += 1
            print("Pesos ajustados")
            print(pesos)
    
    return pesos,qtde_ajuste

Para dar início ao aprendizado colocamos a chamada da função verifica() em loop, onde a condição de parada é a convergência, ou seja, quando não há mais erros para os exemplos no conjunto de treinamento.

In [31]:
ajustes = np.array([])

parar = False
epocas = 0

while(parar==False):
    resultado = verifica(pesos)
    pesos = resultado[0]
    ajustes = np.append(ajustes,[resultado[1]])
    indice = len(ajustes)
    if(ajustes[indice-1] == 0):
        parar = True
    epocas += 1

Pesos ajustados
[ -0.17655766 -53.37901306 -76.5460162 ]
Pesos ajustados
[ -0.27655766  19.41700694 -40.7164562 ]
Pesos ajustados
[ -0.37655766 102.01570694  39.1393738 ]
Pesos ajustados
[ -0.27655766 107.86146694 -39.1552162 ]
Pesos ajustados
[  -0.17655766   67.85255694 -117.0479062 ]
Pesos ajustados
[-7.65576591e-02  1.26295477e+02 -7.54676262e+01]
Pesos ajustados
[  -0.17655766   73.33541694 -132.3370862 ]
Pesos ajustados
[-7.65576591e-02  1.32894937e+02 -8.22147562e+01]
Pesos ajustados
[  -0.17655766   87.37030694 -147.8506862 ]
Pesos ajustados
[-7.65576591e-02  1.01708737e+02 -1.38464466e+02]
Pesos ajustados
[ 2.34423409e-02  1.92424597e+02 -6.37511462e+01]
Pesos ajustados
[-7.65576591e-02  1.34643607e+02 -1.24059296e+02]
Pesos ajustados
[  -0.17655766   84.73378694 -175.3197262 ]
Pesos ajustados
[  -0.27655766  112.55751694 -157.2648062 ]
Pesos ajustados
[  -0.37655766  140.02110694 -136.4084562 ]
Pesos ajustados
[  -0.47655766   71.16542694 -206.4787562 ]
Pesos ajustados
[  -0.

In [32]:
ajustes = ajustes.astype(int)
total_ajustes = np.sum(ajustes)

print('Ao final da execução do algoritmo, podemos verificar que houve um total de ',total_ajustes,' ajuste(s) realizados nos pesos. Para a convergência foram necessárias um total de ',epocas,' épocas. Abaixo pode-se visualizar a quantidade de ajustes realizados em cada época.')
print('')

for i in range(0,len(ajustes)):
    print('Época ',i+1,' => ', ajustes[i],' ajustes')

Ao final da execução do algoritmo, podemos verificar que houve um total de  59  ajuste(s) realizados nos pesos. Para a convergência foram necessárias um total de  3  épocas. Abaixo pode-se visualizar a quantidade de ajustes realizados em cada época.

Época  1  =>  48  ajustes
Época  2  =>  11  ajustes
Época  3  =>  0  ajustes
