# Notebook destinado a Parte 1 - Resolvendo um Problema Linearmente Separável do Projeto 2 de Redes Neurais 2020.1
## Colaboradores: Jakson Protázio e Nadine Brito

Primeiro importamos as bibliotecas necessárias.

In [225]:
import numpy as np
import random

Em seguida realizamos a leitura do dataset. 

In [226]:
dataset=np.fromfile('data/dataAll.txt')
linhas = len(dataset)//3
colunas=3
dataset=dataset.reshape(linhas, colunas)
print(dataset)

[[-363.7884  244.1423    0.    ]
 [ 328.7572 -256.7658    1.    ]
 [-164.9827  613.2164    0.    ]
 ...
 [ 872.4311  669.1192    1.    ]
 [ 822.6894 -702.6489    1.    ]
 [-140.147   734.0983    0.    ]]


No passo seguinte iremos iniciar o preenchimento do vetor de pesos.

In [227]:
pesos = np.array([random.uniform(-0.5,0.5),random.uniform(-0.5,0.5),random.uniform(-0.5,0.5)])
    
print(pesos)

[-0.26305878  0.32293412  0.02343818]


Agora verificamos, através de uma soma ponderada e uma função de ativação, se os pesos precisam de ajuste.

In [228]:
entradas = np.array([[-1, dataset[0,0], dataset[0,1]]])
for i in range(1, linhas):
    entradas = np.append(entradas, [[-1, dataset[i,0], dataset[i,1]]], axis=0)
print(entradas)

[[  -1.     -363.7884  244.1423]
 [  -1.      328.7572 -256.7658]
 [  -1.     -164.9827  613.2164]
 ...
 [  -1.      872.4311  669.1192]
 [  -1.      822.6894 -702.6489]
 [  -1.     -140.147   734.0983]]


In [229]:
def soma(entradas,pesos):
    return(np.dot(entradas,pesos))

In [230]:
def ativacao(saida):
    if(saida >= 0):
        return 1
    else:
        return 0  

In [231]:
def verifica(n):
    qtde_ajuste = 0
    new_pesos = np.array([])
    
    for i in range(n):
        soma_saida = soma(entradas[i], pesos)
        y = ativacao(soma_saida)
        if(y != dataset[i,2]):
            new_pesos = ajusta(pesos,dataset[i,2],y,entradas[i])
            qtde_ajuste += 1
            print('ajustes = ',qtde_ajuste)
    return new_pesos, qtde_ajuste

In [232]:
def ajusta(pesos_atuais, yd, y, x):
    taxa = 0.1
    erro = (yd-y)
    mult = taxa*erro
    result = pesos_atuais + np.dot(mult,x)
    return result

resultado = verifica(linhas)
pesos = resultado[0]
ajustes = resultado[1]

print(pesos)
print(ajustes)

Não precisa de ajuste
Não precisa de ajuste
Não precisa de ajuste
ajustes =  1
ajustes =  2
ajustes =  3
ajustes =  4
Não precisa de ajuste
Não precisa de ajuste
Não precisa de ajuste
ajustes =  5
Não precisa de ajuste
ajustes =  6
ajustes =  7
ajustes =  8
Não precisa de ajuste
Não precisa de ajuste
Não precisa de ajuste
Não precisa de ajuste
Não precisa de ajuste
Não precisa de ajuste
Não precisa de ajuste
Não precisa de ajuste
Não precisa de ajuste
Não precisa de ajuste
Não precisa de ajuste
Não precisa de ajuste
Não precisa de ajuste
Não precisa de ajuste
Não precisa de ajuste
Não precisa de ajuste
ajustes =  9
Não precisa de ajuste
ajustes =  10
Não precisa de ajuste
Não precisa de ajuste
Não precisa de ajuste
ajustes =  11
Não precisa de ajuste
Não precisa de ajuste
Não precisa de ajuste
Não precisa de ajuste
Não precisa de ajuste
Não precisa de ajuste
ajustes =  12
ajustes =  13
ajustes =  14
Não precisa de ajuste
ajustes =  15
Não precisa de ajuste
Não precisa de ajuste
Não pre

In [233]:
a = np.array([1,2,3])
b = np.copy(a)
b

array([1, 2, 3])

In [234]:
pesos[0]

-0.16305878323550368