# Notebook destinado a Parte 1 - Resolvendo um Problema Linearmente Separável do Projeto 2 de Redes Neurais 2020.1
## Colaboradores: Jakson Protázio e Nadine Brito

Primeiro importamos as bibliotecas necessárias.

In [1]:
import numpy as np
import random

Em seguida realizamos a leitura do dataset. 

In [2]:
dataset=np.fromfile('data/dataAll.txt')
linhas = len(dataset)//3
colunas=3
dataset=dataset.reshape(linhas, colunas)
print(dataset)

[[-363.7884  244.1423    0.    ]
 [ 328.7572 -256.7658    1.    ]
 [-164.9827  613.2164    0.    ]
 ...
 [ 872.4311  669.1192    1.    ]
 [ 822.6894 -702.6489    1.    ]
 [-140.147   734.0983    0.    ]]


No passo seguinte iremos iniciar o preenchimento do vetor de pesos.

In [3]:
pesos = np.array([random.uniform(-0.5,0.5),random.uniform(-0.5,0.5),random.uniform(-0.5,0.5)])
    
print(pesos)

[ 0.34669869  0.35596957 -0.28962916]


Agora verificamos, através de uma soma ponderada e uma função de ativação, se os pesos precisam de ajuste.

In [4]:
entradas = np.array([[-1, dataset[0,0], dataset[0,1]]])
for i in range(1, linhas-2):
    entradas = np.append(entradas, [[-1, dataset[i,0], dataset[i,1]]], axis=0)

print(entradas)

[[  -1.     -363.7884  244.1423]
 [  -1.      328.7572 -256.7658]
 [  -1.     -164.9827  613.2164]
 ...
 [  -1.     -738.4556  357.1981]
 [  -1.      438.5813  445.3901]
 [  -1.      872.4311  669.1192]]


In [5]:
def soma(entradas,pesos):
    return(np.dot(entradas,pesos))

In [6]:
def ativacao(saida):
    if(saida >= 0):
        return 1
    else:
        return 0  

In [7]:
def verifica(n):
    for i in range(n):
        soma_saida = soma(entradas[i], pesos)
        print(soma_saida)
        print(ativacao(soma_saida))
        if(ativacao(soma_saida) == 1):
            print('Precisa ajustar os pesos')
        else:
            print('Não precisa de ajuste')

verifica(5)

-200.5550306683894
0
Não precisa de ajuste
191.0477257419691
1
Precisa ajustar os pesos
-236.68087382752296
0
Não precisa de ajuste
-30.890809248622475
0
Não precisa de ajuste
11.924145566362128
1
Precisa ajustar os pesos
