# Notebook destinado a Parte 1 - Resolvendo um Problema Linearmente Separável do Projeto 2 de Redes Neurais 2020.1
## Colaboradores: Jakson Protázio e Nadine Brito

Primeiro importamos as bibliotecas necessárias.

In [163]:
import numpy as np
import random

Em seguida realizamos a leitura do dataset. 

In [164]:
dataset=np.fromfile('data/dataAll.txt')
linhas = len(dataset)//3
colunas=3
dataset=dataset.reshape(linhas, colunas)
print(dataset)

[[-363.7884  244.1423    0.    ]
 [ 328.7572 -256.7658    1.    ]
 [-164.9827  613.2164    0.    ]
 ...
 [ 872.4311  669.1192    1.    ]
 [ 822.6894 -702.6489    1.    ]
 [-140.147   734.0983    0.    ]]


No passo seguinte iremos iniciar o preenchimento do vetor de pesos.

In [165]:
pesos = np.array([random.uniform(-0.5,0.5),random.uniform(-0.5,0.5),random.uniform(-0.5,0.5)])
    
print(pesos)

[-0.21313396 -0.31432754 -0.06174267]


Agora verificamos, através de uma soma ponderada e uma função de ativação, se os pesos precisam de ajuste. Para isso, primeiro, preenchemos um vetor com as entradas do dataset.

In [166]:
entradas = np.array([[-1, dataset[0,0], dataset[0,1]]])
for i in range(1, linhas):
    entradas = np.append(entradas, [[-1, dataset[i,0], dataset[i,1]]], axis=0)
print(entradas)

[[  -1.     -363.7884  244.1423]
 [  -1.      328.7572 -256.7658]
 [  -1.     -164.9827  613.2164]
 ...
 [  -1.      872.4311  669.1192]
 [  -1.      822.6894 -702.6489]
 [  -1.     -140.147   734.0983]]


Agora definimos a função que irá realizar a soma ponderada.

In [167]:
def soma(entradas,pesos):
    return(np.dot(entradas,pesos))

Em seguida definimos a função de ativação. Nesse cenário, a pedido do enunciado, adotou-se a função de ativação degrau com limiar sendo 0.

In [168]:
def ativacao(saida):
    if(saida >= 0):
        return 1
    else:
        return 0  

Definimos também a de ajuste de pesos.

In [169]:
def ajusta(pesos_atuais, yd, y, x):
    taxa = 0.1
    erro = (yd-y)
    mult = taxa*erro
    result = pesos_atuais + np.dot(mult,x)
    return result


A função verifica, será responsável por fazer a chamada das funções para realizar a soma ponderada, função de ativação e a função de ajuste de pesos.

In [170]:
def verifica(pesos):
    qtde_ajuste = 0
    n = len(entradas)
    
    for i in range(n):
        soma_saida = soma(entradas[i], pesos)
        y = ativacao(soma_saida)
        if(y != dataset[i,2]):
            pesos = ajusta(pesos,dataset[i,2],y,entradas[i])
            qtde_ajuste += 1
            print("Pesos ajustados")
            print(pesos)
    
    return pesos,qtde_ajuste

Para dar início ao aprendizado colocamos a chamada da função verifica() em loop, onde a condição de parada é a convergência, ou seja, quando não há mais erros para os exemplos no conjunto de treinamento.

In [171]:
ajustes = np.array([])

parar = False
epocas = 0

while(parar==False):
    resultado = verifica(pesos)
    pesos = resultado[0]
    ajustes = np.append(ajustes,[resultado[1]])
    indice = len(ajustes)
    if(ajustes[indice-1] == 0):
        parar = True
    epocas += 1

Pesos ajustados
[ -0.11313396  36.06451246 -24.47597267]
Pesos ajustados
[-1.31339647e-02 -1.75945375e+01 -1.00971723e+02]
Pesos ajustados
[ -0.11313396  55.20148246 -65.14216267]
Pesos ajustados
[ -0.21313396 137.80018246  14.71366733]
Pesos ajustados
[-1.13133965e-01  1.43645942e+02 -6.35809227e+01]
Pesos ajustados
[-1.31339647e-02  1.03637032e+02 -1.41473613e+02]
Pesos ajustados
[ 8.68660353e-02  1.57306842e+02 -9.23813427e+01]
Pesos ajustados
[-1.31339647e-02  1.04346782e+02 -1.49250803e+02]
Pesos ajustados
[ 8.68660353e-02  1.63906302e+02 -9.91284727e+01]
Pesos ajustados
[-1.31339647e-02  1.18381672e+02 -1.64764403e+02]
Pesos ajustados
[ 8.68660353e-02  2.09097532e+02 -9.00510827e+01]
Pesos ajustados
[-1.31339647e-02  1.51316542e+02 -1.50359233e+02]
Pesos ajustados
[-1.13133965e-01  1.03049982e+02 -1.98828953e+02]
Pesos ajustados
[  -0.21313396  173.49733246 -156.71268267]
Pesos ajustados
[  -0.31313396  126.65533246 -208.12255267]
Pesos ajustados
[  -0.41313396  196.51896246 -143

In [173]:
ajustes = ajustes.astype(int)
total_ajustes = np.sum(ajustes)

print('Ao final da execução do algoritmo, podemos verificar que houve um total de ',total_ajustes,' ajuste(s) realizados nos pesos. Para a convergência foram necessárias um total de ',epocas,' épocas. Abaixo pode-se visualizar a quantidade de ajustes realziados em cada época.')

for i in range(0,len(ajustes)):
    print('Época ',i+1,' => ', ajustes[i],)

Ao final da execução do algoritmo, podemos verificar que houve um total de  24  ajuste(s) realizados nos pesos. Para a convergência foram necessárias um total de  2  épocas. Abaixo pode-se visualizar a quantidade de ajustes realziados em cada época.
[24  0]
