# Notebook destinado a Parte 1 - Resolvendo um Problema Linearmente Separável do Projeto 2 de Redes Neurais 2020.1
## Colaboradores: Jakson Protázio e Nadine Brito

Primeiro importamos as bibliotecas necessárias.

In [9]:
import numpy as np
import random

Em seguida realizamos a leitura do dataset. 

In [10]:
dataset=np.fromfile('data/dataAll.txt')
linhas = len(dataset)//3
colunas=3
dataset=dataset.reshape(linhas, colunas)
print(dataset)

[[-363.7884  244.1423    0.    ]
 [ 328.7572 -256.7658    1.    ]
 [-164.9827  613.2164    0.    ]
 ...
 [ 872.4311  669.1192    1.    ]
 [ 822.6894 -702.6489    1.    ]
 [-140.147   734.0983    0.    ]]


No passo seguinte iremos iniciar o preenchimento do vetor de pesos.

In [11]:
pesos = np.array([random.uniform(-0.5,0.5),random.uniform(-0.5,0.5),random.uniform(-0.5,0.5)])
    
print(pesos)

[ 0.38806667  0.21148311 -0.10975892]


Agora verificamos, através de uma soma ponderada e uma função de ativação, se os pesos precisam de ajuste.

In [12]:
entradas = np.array([[-1, dataset[0,0], dataset[0,1]]])
for i in range(1, linhas-2):
    entradas = np.append(entradas, [[-1, dataset[i,0], dataset[i,1]]], axis=0)

print(entradas)

[[  -1.     -363.7884  244.1423]
 [  -1.      328.7572 -256.7658]
 [  -1.     -164.9827  613.2164]
 ...
 [  -1.     -738.4556  357.1981]
 [  -1.      438.5813  445.3901]
 [  -1.      872.4311  669.1192]]


In [13]:
def soma(entradas,pesos):
    return(np.dot(entradas,pesos))

In [14]:
def ativacao(saida):
    if(saida >= 0):
        return 1
    else:
        return 0  

In [15]:
def verifica(n):
    for i in range(n):
        soma_saida = soma(entradas[i], pesos)
        y = ativacao(soma_saida)
        print(y)
        
        if(ativacao(soma_saida) == 1):
            print('Precisa ajustar os pesos')
            ajusta(pesos, dataset[i][2], y, entradas[i])
        else:
            print('Não precisa de ajuste')


verifica(5)

0
Não precisa de ajuste
1
Precisa ajustar os pesos
[ 0.38806667  0.21148311 -0.10975892]
0
Não precisa de ajuste
1
Precisa ajustar os pesos
[  0.48806667 -53.44756689 -76.60550892]
1
Precisa ajustar os pesos
[  0.48806667 -31.21148689 -34.49350892]


In [16]:
def ajusta(peso_atual, yd, y, x):

    taxa = 0.1
    erro = (yd-y)
    print(peso_atual + (taxa*erro*x))
    #return(peso_atual + (taxa*erro*x))